### PR TITLE
Make more secure

### LINKED ISSUE #45: When there is no internet connection, the app crashes
### Before you start...

- [X] Have you updated the FluentHub? You might be using an old version.
- [X] Have you checked if similar issue have already been reported?

### What windows are you seeing the problem on?

Windows 11 Dev

### What FluentHub version/architecture are you seeing the problem on?

_None_

### Description

As the title

### Steps To Reproduce

1. Open app with no internel connection

### Expected behavior

_No response_

### Relevant Assets

_No response_

### LINKED ISSUE #56: Migrate Octokit.NET to Octokit.GraphQL.NET
**Additional context**
### Before you start...

- [X] Have you updated the FluentHub? You might be using an old version.
- [X] Have you checked if similar issue have already been reported?

### What windows are you seeing the problem on?

Windows 11

### What FluentHub version/architecture are you seeing the problem on?

_None_

### Description

As the title

### Steps To Reproduce

_No response_

### Expected behavior

_No response_

### Relevant Assets

_No response_

### LINKED ISSUE #95: Organization OAuth Access Restriction
### Before you start...

- [X] Have you updated the FluentHub? You might be using an old version.
- [X] Have you checked if similar issue have already been reported?

### What windows are you seeing the problem on?

Windows 11

### What FluentHub version/architecture are you seeing the problem on?

Fluenthub v0.8.13

### Description

An exception occurs.

https://docs.github.com/en/organizations/restricting-access-to-your-organizations-data

### Steps To Reproduce

1. Go to the organization page without member access rights.

### Expected behavior

Ensure that no exceptions are raised

use try-catch?

### Relevant Assets

_No response_

### PR DESCRIPTION
**Pull request by onein528**
### Before you start...

- [x] Have you updated the FluentHub? You might be using an old version.
- [x] Have you checked if similar issue have already been reported?

### Resolved / Related Issues

- Closes #45
- Closes #56 
- Closes #95

### Details of Changes

- [ ] Handle all exceptions
- [ ] Display message when an exception occured
- [x] Colored repo's code block

### Validation

- [x] Built and ran the app
- [x] Tested the changes for accessibility

### Relevant Assets

image

### CODE REVIEW

**Comment by onein528** [comment]
nice!

image

**Comment by onein528** [comment]
Should I catch the exception in the main thread(viewmodel) to get the error message? @luandersonn

**Comment by luandersonn** [comment]
@onein528 Yes. Or you can use `DispatcherQueue` to update the UI.

**Comment by onein528** [comment]
haha i dont knwo sorry.

**Comment by luandersonn** [comment]
After the dddd5d15db442bb3f3db68bde7a018c5293bad26, you can send Notifications from any thread

**Comment by onein528** [comment]
ok

**Comment by onein528** [comment]
when theres no internet:

image

File: src/FluentHub/ViewModels/Users/DiscussionsViewModel.cs [hunk 1]
```diff
@@ -53,6 +57,15 @@ private async Task RefreshDiscussionsAsync(string username)
             catch (Exception ex)
             {
                 _logger?.Error("RefreshDiscussionsAsync", ex);
+                if (_messenger != null)
+                {
+                    UserNotificationMessage notification = new("Something went wrong", ex.Message, UserNotificationType.Error);
+                    _messenger.Send(notification);
+                }
+                else
```
Comment (luandersonn) [inline src/FluentHub/ViewModels/Users/DiscussionsViewModel.cs]: Remove the `else`, throw the exception to the Discussions page so that it knows when to show the "refresh" button

Comment (onein528) [reply src/FluentHub/ViewModels/Users/DiscussionsViewModel.cs]: ok

**Comment by onein528** [comment]
updated UI

**Comment by luandersonn** [comment]
On a4aedfc12182320727b355e41167ddf5c29f2f58
- Add CancellationToken to ViewModel commands
- Add Empty/Error State to some Views
- Code refactoring

**Comment by onein528** [comment]
If you feel you've got secure(any likely exceptions handled and...).

**Comment by onein528** [comment]
i think it is high time to merge this.

**Review by trustedmember — APPROVED** [review]

**Comment by trustedmember** [comment]
Need final adjustment.

- Fix margins.
- Check changes if you expeced.

**Comment by onein528** [comment]
sub commit message:

+ Add FluentHub.Backend.
+ Update README.md.
+ Update some documentations.
+ Add customized logger.
- Remove duplicated codes.
+ Add "Async" suffix to all async queries.
+ Update authorization method.
+ Add a converter ObjectToBoolConverter.
+ Update most ViewModel to DepencenctInjection.
+ Add notification infobar.
+ Update navigation service
+ Update to catch all exception from Octokit.
+ Add option to copy git clone command
+ Allow a viewer to access the .Viewer query when viewer viewing a page.

Co-authored-by: Luandersonn Airton <luandersonn@outlook.com>
Co-authored-by: Gabriel Fontán <gabilessto@gmail.com>
